export enum Hardfork {
    Chainstart = 'chainstart',
    Homestead = 'homestead',
    Dao = 'dao',
    TangerineWhistle = 'tangerineWhistle',
    SpuriousDragon = 'spuriousDragon',
    Byzantium = 'byzantium',
    Constantinople = 'constantinople',
    Petersburg = 'petersburg',
    Istanbul = 'istanbul',
    MuirGlacier = 'muirGlacier',
    Berlin = 'berlin',
    London = 'london',
    ArrowGlacier = 'arrowGlacier',
    GrayGlacier = 'grayGlacier',
    MergeForkIdTransition = 'mergeForkIdTransition',
    Paris = 'paris',
    Shanghai = 'shanghai',
    Cancun = 'cancun',
    Prague = 'prague',
    Osaka = 'osaka',
}